language: java
services:
  - docker

jdk:
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea

script:
  - mvn package jib:dockerBuild

after_success:
  - bash <(curl -s https://codecov.io/bash)

